version: '3.8'

services:
  python-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-analysis
    ports:
      - "8000:8000"
    networks:
      - crm-network

networks:
  crm-network:
    external: true