[project]
name = "crm-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "polars==1.27.1",  # FIXME: higher versions are failing the tests
    "pydantic-settings",
    "requests",
]

[project.optional-dependencies]
development = [
  "ruff",
]

testing = [
    "httpx2",
    "pytest",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I"]
