[project]
name = "crm-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "httpx>=0.27.2",
    "polars>=1.12.0",
    "pydantic-settings>=2.6.0",
    "pytest>=8.3.3",
    "requests>=2.32.3",
    "ruff>=0.7.1",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["I"]
